version: '3'
services:
  web:
    build: .
    volumes:
      - .:/rails
    command: ["bin/rails", "server", "-b", "0.0.0.0"]
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    user: root
    environment:
      RAILS_ENV: development
      SECRET_KEY_BASE: dummydummydummydummydummydummydummy
    depends_on:
      - db

  db:
    image: mysql:8.2.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  mysql-data:
